const list = [
    {
      id: 1,
      title: "Pedigree Pro Puppy, Large Breed (3-18 Months) Dry Dog Food, 20 Kg Pack, Chicken",
      price: 2999,
      img: "https://m.media-amazon.com/images/I/61BPw3CVmxL._SX679_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 2,
      title: "Pedigree Wet Food for Adult Dogs, Chicken & Liver Chunks in Gravy Flavour, Pack of 15 (15 x 70g)",
      price: 599,
      img: "https://m.media-amazon.com/images/I/61NBdi6v4sL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 3,
      title: "Pedigree Biscrok Biscuits Dog Treats (Above 4 Months), Chicken Flavor, 900g Pack",
      price: 290,
      img: "https://m.media-amazon.com/images/I/81Wm0e6AlpL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 4,
      title: "Drools Adult Dry Dog Food Chicken and Egg, 3kg with Free 1.2kg, Total 4.2 kg Pack",
      price: 719,
      img: "https://m.media-amazon.com/images/I/71NrhVNqHhL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 5,
      title: "Drools Adult Dry Cat Food, Ocean Fish, 3kg with Free 1.2kg, Tatal 4.2 Kg Pack",
      price: 949,
      img: "https://m.media-amazon.com/images/I/71boQDCSO7L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 6,
      title: "BarkButler x Fofos Super Durable Bounce Toys for Dogs (S) | Yellow & Grey Dog Ball | X-Small-Medium Dogs (0-20 kg)",
      price: 573,
      img: "https://m.media-amazon.com/images/I/71WZuBAO4NL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 7,
      title: "Kennel Kitchen Chicken Chunks in Gravy, 80g (Pack of 30) | Wet Dog Food for Adult & Puppy | Dog Food Gravy with Regionally Sourced Fresh Chicken",
      price: 1199,
      img: "https://m.media-amazon.com/images/I/91oznyN4AML._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 8,
      title: "Kennel Kitchen Tuna in Jelly,12 x 80g Each. Grain Free Wet Cat Food for Adults and Kittens",
      price: 510,
      img: "https://m.media-amazon.com/images/I/41iJXpsOtTL._SX300_SY300_QL70_FMwebp_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 9,
      title: "Kennel Kitchen Gourmet Loaf Chicken with Superfood Carrots & Moringa, 80g (Pack of 6) | Wet Food for Adult Dogs in Cups ",
      price: 299,
      img: "https://m.media-amazon.com/images/I/81qlMazS+LL._SX679_PIbundle-6,TopRight,0,0_AA679SH20_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 10,
      title: "M-Pets Pet Cleaning Wipes - Body & Paws - 80 pcs",
      price: 515,
      img: "https://m.media-amazon.com/images/I/51uMPDYbf-L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 11,
      title: "M-PETS Puppy Training Pads 30 PCS (45 X 60 CMS)",
      price: 872,
      img: "https://m.media-amazon.com/images/I/41p3XKicAwL.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 12,
      title: "Moe Xtra Nourish Pet Shampoo for Itch Relief & Moisturize Dry Coat| Helps Soothe Itchy Skin | Sulfate & Paraben Free | pH Balanced for Dogs & Cats (300ml)",
      price: 597,
      img: "https://m.media-amazon.com/images/I/61lWawtSJ7L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },

    {
      id: 1,
      title: "Pedigree Pro Puppy, Large Breed (3-18 Months) Dry Dog Food, 20 Kg Pack, Chicken",
      price: 2999,
      img: "https://m.media-amazon.com/images/I/61BPw3CVmxL._SX679_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 2,
      title: "Pedigree Wet Food for Adult Dogs, Chicken & Liver Chunks in Gravy Flavour, Pack of 15 (15 x 70g)",
      price: 599,
      img: "https://m.media-amazon.com/images/I/61NBdi6v4sL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 3,
      title: "Pedigree Biscrok Biscuits Dog Treats (Above 4 Months), Chicken Flavor, 900g Pack",
      price: 290,
      img: "https://m.media-amazon.com/images/I/81Wm0e6AlpL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 4,
      title: "Drools Adult Dry Dog Food Chicken and Egg, 3kg with Free 1.2kg, Total 4.2 kg Pack",
      price: 719,
      img: "https://m.media-amazon.com/images/I/71NrhVNqHhL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 5,
      title: "Drools Adult Dry Cat Food, Ocean Fish, 3kg with Free 1.2kg, Tatal 4.2 Kg Pack",
      price: 949,
      img: "https://m.media-amazon.com/images/I/71boQDCSO7L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 6,
      title: "BarkButler x Fofos Super Durable Bounce Toys for Dogs (S) | Yellow & Grey Dog Ball | X-Small-Medium Dogs (0-20 kg)",
      price: 573,
      img: "https://m.media-amazon.com/images/I/71WZuBAO4NL._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 7,
      title: "Kennel Kitchen Chicken Chunks in Gravy, 80g (Pack of 30) | Wet Dog Food for Adult & Puppy | Dog Food Gravy with Regionally Sourced Fresh Chicken",
      price: 1199,
      img: "https://m.media-amazon.com/images/I/91oznyN4AML._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 8,
      title: "Kennel Kitchen Tuna in Jelly,12 x 80g Each. Grain Free Wet Cat Food for Adults and Kittens",
      price: 510,
      img: "https://m.media-amazon.com/images/I/41iJXpsOtTL._SX300_SY300_QL70_FMwebp_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 9,
      title: "Kennel Kitchen Gourmet Loaf Chicken with Superfood Carrots & Moringa, 80g (Pack of 6) | Wet Food for Adult Dogs in Cups ",
      price: 299,
      img: "https://m.media-amazon.com/images/I/81qlMazS+LL._SX679_PIbundle-6,TopRight,0,0_AA679SH20_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 10,
      title: "M-Pets Pet Cleaning Wipes - Body & Paws - 80 pcs",
      price: 515,
      img: "https://m.media-amazon.com/images/I/51uMPDYbf-L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 11,
      title: "M-PETS Puppy Training Pads 30 PCS (45 X 60 CMS)",
      price: 872,
      img: "https://m.media-amazon.com/images/I/41p3XKicAwL.jpg",
      amount: 1,
      discount:'42%',
    },
    {
      id: 12,
      title: "Moe Xtra Nourish Pet Shampoo for Itch Relief & Moisturize Dry Coat| Helps Soothe Itchy Skin | Sulfate & Paraben Free | pH Balanced for Dogs & Cats (300ml)",
      price: 597,
      img: "https://m.media-amazon.com/images/I/61lWawtSJ7L._AC_UL480_FMwebp_QL65_.jpg",
      amount: 1,
      discount:'42%',
    },
];

export default list;